stages:
  data_ingestion:
    cmd: python -m emotional_tweet.dataset
    deps:
    - emotional_tweet/dataset.py
    params:
    - data_ingestion
    outs:
    - data/raw
  data_preprocessing:
    cmd: python -m emotional_tweet.data_preprocessing
    deps:
    - data/raw
    - emotional_tweet/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python -m emotional_tweet.features
    deps:
    - data/processed
    - emotional_tweet/features.py
    params:
    - feature_engineering
    outs:
    - data/features
  model_building:
    cmd: python -m emotional_tweet.modeling.train
    deps:
    - data/features
    - emotional_tweet/modeling/train.py
    params:
    - model_building
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python -m emotional_tweet.modeling.predict
    deps:
    - data/features
    - emotional_tweet/modeling/predict.py
    - models/model.pkl
    metrics:
    - reports/metrics_dict.json:
        cache: false
